### ISSUE TITLE
Improve algorithm

### ISSUE THREAD

**Issue by rajkumaar23** [ayushjainrksh/conactivity#31]
**Is your feature request related to a problem? Please describe.**
Yes, it is a waste of bandwidth and time revisiting the profiles list page (because of `.back()`) after browsing the recent activity of every user.

**Describe the solution you'd like**
Instead, initially all the users' profile links of 2 (or) whatever the max number of pages to traverse can be **cached** into an array in memory before-hand and the same can be used for traversing each. This will remove the unnecessary usage of `.back()`. Rather, we can traverse through the array and basically visit one profile after other.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ayushjainrksh** [comment]
@rajkumaar23 This sounds like a good enhancement. Feel free to open a PR for the same.

**Comment by rajkumaar23** [comment]
@ayushjainrksh Sure
