### ISSUE TITLE
Iterate over the list of profileListSelectors

### ISSUE THREAD

**Issue by ayushjainrksh** [ayushjainrksh/conactivity#39]
**Is your feature request related to a problem? Please describe.**
Generalize this section of code to use a loop instead of hardcoding array indexes. This would be useful if we want to add any more profileListSelectors in the future. Moreover, generalizing it would help in code clarity (Add comments to explain the approach in the code).

**https://github.com/ayushjainrksh/conactivity/blob/83c3c40fdbe8d88679eca637f018fabacf14bdf2/scrape.js#L110-L114**

**Additional context**
To understand what this piece of code does, go through #30

**Comment by vivek32ta** [comment]
Hi @ayushjainrksh 

I'd like to take this up!

Best,
Vivek

**Comment by sakshi-s** [comment]
Hey I would like to take this up. We can iterate over profileListSelectors array and evaluate profileListNodes in the loop.

**Comment by ayushjainrksh** [comment]
@sakshi-s This issue has probably been fixed in #40. I'm still to review it though. You can pick up any other unresolved issue or open a new issue/feature request you would like to work on. I'll open some more issues in upcoming days, so keep a close eye!

**Comment by sakshi-s** [comment]
Sure, thanks!
