### ISSUE TITLE
Add function descriptions in jsdocs format

### ISSUE THREAD

**Issue by ayushjainrksh** [ayushjainrksh/conactivity#45]
**Describe the bug**
The newly added functions do not have function jsdocs to explain their functionality.

**Expected behavior**
Add a jsdocs on the top of each function just like the function `scrapeLinkedIn`.

**Comment by StaniPetrosyan** [comment]
Hi, can I work on this ?

**Comment by ayushjainrksh** [comment]
@StaniPetrosyan  Yeah sure.
