### ISSUE TITLE
Save links to a file for future use

### ISSUE THREAD

**Issue by ayushjainrksh** [ayushjainrksh/conactivity#7]
**Is your feature request related to a problem? Please describe.**
The results of the scraping are displayed on the terminal. A good to have feature would be to add the scraped profile links to a file if the user wants to look back or connect with someone else.

**Describe the solution you'd like**
- The output can be appended to a file with the name of the company inside a folder.
- Add the folder to .gitignore.

**Describe alternatives you've considered**
Printing on terminal is what we have for now

**Comment by cwille97** [comment]
Hey, I am going to start working on this issue. Do you mind if I submit the pull request on the morning of October 1st for Hacktoberfest?

**Comment by ayushjainrksh** [comment]
Sure, no problem. Go ahead and let me know if you need any help :)
